name:                saison3
version:             0.1.0.0
github:              "githubuser/saison3"
license:             BSD3
author:              "Author name here"
maintainer:       T JO  "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/saison3#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- split
- hspec
- hspec-discover
- array
- servant
- servant-server
- wai
- warp

library:
  source-dirs: src

executables:
  saison3-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - saison3

tests:
  saison3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - saison3
    - hspec
    - hspec-discover
    - hspec-wai
    - hspec-wai-json
    - split
    - array
    - wai
    - wai-extra
